apiVersion: v1
kind: Pod 
metadata:
      name: pod1
      labels: 
        label1: x
spec:
  containers:
    - image: abdallah76/osproj
      name: cont1
      ports: 
        - containerPort: 80
      imagePullPolicy: IfNotPresent
      resources: 
        limits: 
          memory: "100Mi"